# Travis build configuration
# https://docs.travis-ci.com/user/customizing-the-build/
sudo: required

dist: bionic

language: cpp

os:
  - linux
  - osx

arch:
  - arm64

env:
  matrix:
    - CONFIG=release

install:
 # extra-cmake-modules not present in precise (needed for openexr)
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get -qq update
      && sudo apt-get install -y mesa-common-dev libgl1-mesa-dev
      && sudo apt-get install -y qtbase5-dev
      && sudo apt-get install -y libpng-dev libgsl-dev libgsl-dbg libgomp1 liblzo2-2 liblzo2-dev
      && sudo apt-get install -y libtiff5
      && sudo apt-get install -y libsndfile1-dev tree
      && sudo apt-get install -y extra-cmake-modules
      && gcc --version
      && lsb_release -a
      ;
    else
         brew update > /dev/null
      && brew install qt5 gsl llvm lzo libsndfile tree
      && export CC=/usr/local/opt/llvm/bin/clang
      && export CXX=/usr/local/opt/llvm/bin/clang++
      && export LDFLAGS="-L/usr/local/opt/llvm/lib $LDFLAGS"
      && export CPPFLAGS="-I/usr/local/opt/llvm/include $CPPFLAGS"
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

script:
#build
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
         QTDIR="/usr/local/opt/qt5"
      && PATH="$QTDIR/bin:$PATH"
      && LDFLAGS=-L$QTDIR/lib
      && CPPFLAGS=-I$QTDIR/include
      ;
    fi
  - mkdir mandelbulber2/build
  - cd mandelbulber2/build
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         qmake ../qmake/mandelbulber.pro
      ;
    else
         qmake -spec macx-xcode ../qmake/mandelbulber.pro
      && qmake -project
      && qmake -o makefile ../qmake/mandelbulber.pro
      ;
    fi
  - make -j3
  - tree .

# testing
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      cd ..
      && mkdir package
      && ./make-package.sh test package
      && cp build/mandelbulber2 package/mandelbulber2-test/usr/bin/mandelbulber2
      && cd package/mandelbulber2-test
      && ./install
      && mandelbulber2 --test
      ;
    else
         echo 'TODO test...'
      ;
    fi

notifications:
  email:
    - buddhi1980@gmail.com
    - sebastian.jennen@gmx.de
    - robertpancoast77@gmail.com
  webhooks:
    - https://webhooks.gitter.im/e/045502f8fca741c11771
